#!/usr/bin/env python3
import argparse
from classes import Templater

parser = argparse.ArgumentParser()
parser.add_argument('-n', '--name')
parser.add_argument('-t', '--template')

if __name__ == '__main__':
    args = parser.parse_args()
    if not args.name:
        raise ValueError("No name; -n")
    if not args.template:
        raise ValueError("No template; -t")

    templater = Templater(args.name, args.template)
